[build]
  publish = "."

# Redirect URL pulite → file HTML

[[redirects]]
  from = "/come-funziona"
  to = "/come-funziona.html"
  status = 200

[[redirects]]
  from = "/piattaforma"
  to = "/piattaforma.html"
  status = 200

[[redirects]]
  from = "/servizi"
  to = "/servizi.html"
  status = 200


[[redirects]]
  from = "/prezzi"
  to = "/prezzi.html"
  status = 200

[[redirects]]
  from = "/prova-gratuita"
  to = "/prova-gratuita.html"
  status = 200

[[redirects]]
  from = "/contatti"
  to = "/contatti.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/grazie"
  to = "/grazie.html"
  status = 200
